import { GlowCard } from "@/components/ui/spotlight-card"
import { ArrowUpRight, Github, Globe, GitFork, Star } from "lucide-react"

const projects = [
  {
    title: "CampuSign",
    description: "Decentralized event ticketing and QR-based attendance tracking using NFTs to prevent ticket fraud and track engagement for college events.",
    longDesc: "CampuSign solves the issues of ticket counterfeiting and manual attendance tracking at campus events. Organizers mint event tickets as NFT passes. Attendees present a dynamic QR code generated by their wallet that is scanned by organizers to log presence and distribute on-chain participation credentials.",
    tags: ["Solidity", "Next.js", "ERC-721", "Hardhat", "viem"],
    github: "https://github.com",
    demo: "https://example.com",
    metrics: { stars: 18, forks: 4 },
    color: "blue" as const
  },
  {
    title: "CertiLedger",
    description: "Secure academic credentials issuance and instant public validation platform on-chain, eliminating forged university certificates.",
    longDesc: "CertiLedger offers a tamper-proof repository for diplomas and transcripts. The college administration uploads a cryptographic hash of each issued document to the blockchain. Verification is instant: employers upload a student's certificate PDF to the web portal, which computes its hash and cross-references it with the ledger.",
    tags: ["Solidity", "IPFS", "Polygon", "Ethers.js", "React"],
    github: "https://github.com",
    demo: "https://example.com",
    metrics: { stars: 22, forks: 6 },
    color: "purple" as const
  },
  {
    title: "EduDAO",
    description: "On-chain governance and project funding allocation platform for student chapters and college groups.",
    longDesc: "EduDAO automates and transparency-enforces the distribution of club budgets. Members can submit funding proposals for student projects. Token holders (students/mentors) vote on proposals on-chain, and funds are automatically released from a multisig treasury upon passing.",
    tags: ["Solidity", "ERC-20", "Gnosis Safe", "Next.js", "Tailwind"],
    github: "https://github.com",
    demo: "https://example.com",
    metrics: { stars: 15, forks: 3 },
    color: "orange" as const
  }
]

export default function Projects() {
  return (
    <div className="text-white pt-24 pb-16">
      {/* Page Header */}
      <section className="mx-auto max-w-7xl px-6 lg:px-8 text-center space-y-4">
        <p className="text-xs font-semibold uppercase tracking-[0.3em] text-fuchsia-400">
          Our Repository
        </p>
        <h1 className="font-display text-4xl font-extrabold sm:text-5xl md:text-6xl">
          Student-Built Web3 Products
        </h1>
        <p className="mx-auto max-w-3xl text-slate-300 text-sm sm:text-base leading-relaxed">
          Explore the decentralized applications, protocols, and developer tools designed, built, and shipped by members of the LFDT PCCOE Student Chapter.
        </p>
      </section>

      {/* Projects Grid */}
      <section className="mx-auto max-w-7xl px-6 py-16 lg:px-8">
        <div className="grid gap-8 lg:grid-cols-3">
          {projects.map((project, idx) => (
            <GlowCard
              key={idx}
              customSize={true}
              glowColor={project.color}
              className="p-6 h-full flex flex-col justify-between"
            >
              <div className="space-y-4">
                {/* Header */}
                <div className="flex items-center justify-between">
                  <h2 className="font-display text-xl font-bold text-white">{project.title}</h2>
                  <div className="flex gap-2">
                    <a
                      href={project.github}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="p-1.5 rounded-lg bg-white/5 text-slate-400 hover:text-white transition"
                      aria-label="GitHub Repository"
                    >
                      <Github className="h-4 w-4" />
                    </a>
                    <a
                      href={project.demo}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="p-1.5 rounded-lg bg-white/5 text-slate-400 hover:text-white transition"
                      aria-label="Live Demo"
                    >
                      <Globe className="h-4 w-4" />
                    </a>
                  </div>
                </div>

                {/* Content */}
                <p className="text-sm text-slate-300 leading-relaxed">
                  {project.longDesc}
                </p>
              </div>

              {/* Footer and Tags */}
              <div className="mt-8 space-y-4 pt-4 border-t border-white/5">
                <div className="flex flex-wrap gap-1.5">
                  {project.tags.map((tag) => (
                    <span
                      key={tag}
                      className="rounded-full bg-slate-900 border border-white/5 px-2.5 py-0.5 text-xs text-slate-400 font-mono"
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                <div className="flex items-center gap-4 text-xs text-slate-400">
                  <div className="flex items-center gap-1">
                    <Star className="h-3.5 w-3.5 text-amber-400" />
                    {project.metrics.stars} stars
                  </div>
                  <div className="flex items-center gap-1">
                    <GitFork className="h-3.5 w-3.5 text-cyan-400" />
                    {project.metrics.forks} forks
                  </div>
                </div>
              </div>
            </GlowCard>
          ))}
        </div>
      </section>

      {/* Contribute CTA */}
      <section className="mx-auto max-w-4xl px-6 pt-8">
        <div className="relative overflow-hidden rounded-2xl border border-white/5 bg-slate-900/40 p-8 text-center space-y-4">
          <h2 className="font-display text-2xl font-bold">Open Source & Public Good</h2>
          <p className="text-sm text-slate-300 max-w-xl mx-auto">
            Everything we build at LFDT is open source. If you want to contribute, submit a pull request, or report a bug, check out our shared GitHub organization.
          </p>
          <div className="pt-2">
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-5 py-2.5 text-xs font-semibold text-white transition hover:bg-white/10"
            >
              <Github className="h-4 w-4" />
              Visit our Organization
            </a>
          </div>
        </div>
      </section>
    </div>
  )
}
